project:
  type: book
  output-dir: docs
  resources:
    - quarto_safe_map/**

execute:
  echo: true
  warning: false

book:
  title: "Exploratory Analysis of U.S. Campaign Finance Data"
  author:
    - Ayush Kumar (ak5486)
    - Aditi Mittal (am6845)
  repo-url: https://github.com/vitarka101/FEC-US-Campaign-Finance-Analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - analysis.qmd
    - interactive.qmd
    - conclusion.qmd

format:
  html:
    theme: Simplex
    code-fold: true
    allow-html: true
